const styles = {
  // ─── Login ───────────────────────────────────────────────────────────────
  loginPage: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#f1f5f9",
    fontFamily: "'Segoe UI', sans-serif",
  },
  loginCard: {
    background: "#fff",
    borderRadius: 16,
    padding: "40px 36px",
    width: 380,
    boxShadow: "0 4px 24px rgba(0,0,0,0.10)",
  },
  loginHeader: { textAlign: "center", marginBottom: 32 },
  loginIcon: { fontSize: 40 },
  loginTitle: { margin: "8px 0 4px", fontSize: 26, fontWeight: 700, color: "#1e293b" },
  loginSubtitle: { margin: 0, fontSize: 14, color: "#64748b" },
  loginForm: { display: "flex", flexDirection: "column", gap: 16 },
  inputGroup: { display: "flex", flexDirection: "column", gap: 6 },
  label: { fontSize: 13, fontWeight: 600, color: "#374151" },
  input: {
    padding: "10px 14px",
    borderRadius: 8,
    border: "1.5px solid #e2e8f0",
    fontSize: 14,
    outline: "none",
    color: "#1e293b",
  },
  loginBtn: {
    padding: "12px",
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    marginTop: 4,
  },
  errorBox: {
    background: "#fef2f2",
    border: "1px solid #fca5a5",
    color: "#dc2626",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 13,
    margin: "0 24px",
  },

  // ─── Dashboard ───────────────────────────────────────────────────────────
  dashPage: {
    minHeight: "100vh",
    background: "#0f172a",
    fontFamily: "'Segoe UI', sans-serif",
    display: "flex",
    flexDirection: "column",
  },

  // ─── Header ──────────────────────────────────────────────────────────────
  header: {
    background: "#1e293b",
    color: "#fff",
    padding: "14px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottom: "1px solid #334155",
  },
  headerLeft: { display: "flex", alignItems: "center", gap: 12 },
  headerIcon: { fontSize: 28 },
  headerTitle: { fontSize: 20, fontWeight: 700, color: "#f1f5f9" },
  headerSub: { fontSize: 12, color: "#94a3b8", marginTop: 2 },
  headerRight: { display: "flex", alignItems: "center", gap: 16 },
  statsInline: { display: "flex", gap: 12, alignItems: "center" },
  statBadgeFree: {
    background: "#166534",
    color: "#bbf7d0",
    padding: "4px 12px",
    borderRadius: 20,
    fontSize: 13,
    fontWeight: 600,
  },
  statBadgeOccupied: {
    background: "#7f1d1d",
    color: "#fecaca",
    padding: "4px 12px",
    borderRadius: 20,
    fontSize: 13,
    fontWeight: 600,
  },
  statBadgeTotal: { color: "#94a3b8", fontSize: 13 },
  headerUser: { fontSize: 13, color: "#cbd5e1" },
  logoutBtn: {
    background: "transparent",
    border: "1px solid #475569",
    color: "#cbd5e1",
    padding: "6px 14px",
    borderRadius: 6,
    fontSize: 13,
    cursor: "pointer",
  },

  // ─── Parking Area ────────────────────────────────────────────────────────
  parkingArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    padding: "32px 40px",
    gap: 16,
  },
  rowLabel: {
    fontSize: 13,
    fontWeight: 700,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 4,
  },
  slotRow: {
    display: "flex",
    gap: 10,
    flexWrap: "nowrap",
  },

  // ─── Road Divider ─────────────────────────────────────────────────────────
  roadDivider: {
    height: 48,
    background: "#1e293b",
    borderTop: "3px dashed #334155",
    borderBottom: "3px dashed #334155",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "8px 0",
  },
  roadLabel: {
    color: "#475569",
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 2,
  },

  // ─── Slot Cards ──────────────────────────────────────────────────────────
  slotCard: {
    flex: 1,
    minWidth: 0,
    height: 250,
    borderRadius: 10,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    border: "2px solid",
    cursor: "default",
  },
  slotFree: {
    background: "#052e16",
    borderColor: "#16a34a",
    color: "#4ade80",
  },
  slotOccupied: {
    background: "#2d0a0a",
    borderColor: "#dc2626",
    color: "#f87171",
  },
  slotUnknown: {
    background: "#1e293b",
    borderColor: "#334155",
    color: "#475569",
  },
  slotNumber: { fontSize: 40, fontWeight: 800, letterSpacing: 0.5 },
  slotStatusText: { fontSize: 23, fontWeight: 700, letterSpacing: 1.5 },

  // ─── Footer ──────────────────────────────────────────────────────────────
  footer: {
    background: "#1e293b",
    borderTop: "1px solid #334155",
    padding: "12px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  legend: { display: "flex", gap: 20, fontSize: 13 },
  legendFree: { color: "#4ade80" },
  legendOccupied: { color: "#f87171" },
  legendUnknown: { color: "#475569" },
  lastUpdated: { fontSize: 12, color: "#64748b" },
  refreshBtn: {
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
};

export default styles;